### ISSUE TITLE
reboot hangs

### ISSUE THREAD

**Issue by bryfry** [mrfixit2001/debian_builds#10]
I think this issue is similar to this [thread](https://forum.pine64.org/showthread.php?tid=6785).  I don't have a serial cable adapter yet to diagnose further but I am getting the same behavior where reboots hang. 

I'm running the latest release on a rockpro64 board

**Comment by mrfixit2001** [comment]
Thank you for reaching out! The release has a number of kernel fixes and updates since March, and it also now has the latest rockchip uboot. I expect that this should have resolved any reboot issues being experienced, as I have not been able to reproduce the issue myself.
