### ISSUE TITLE
Provide instructions to recreate the build

### ISSUE THREAD

**Issue by ian-kelling** [mrfixit2001/debian_builds#19]
For people to be able to expand on this and build on your work, please provide instructions on how to recreate your build. For example, the readme describes "MrFixIt's custom bootup service." Where is the source code to that? We should not have to go spelunking into a binary image.

**Comment by mrfixit2001** [comment]
Thanks for asking!
There is no binary image for the bootup service, or any other customization included in these builds. They are all bash scripts, included in the images, and can be viewed using any text editor. These builds are generated with the standard debian bootstrapper, and use my kernel and uboot repos. The only customized parts after that have been included in the documentation.

**Comment by ian-kelling** [comment]
Thanks for the clarification.
