### ISSUE TITLE
HDMI audio has to be configured manually plus no audio from headphones

### ISSUE THREAD

**Issue by ghost** [mrfixit2001/debian_builds#2]
I needed to manually enable hdmi audio by following this guide https://wiki.archlinux.org/index.php/PulseAudio/Examples#Set_the_default_output_source but doing the same for the headphone jack did not yield any results. Could this be a kernel issue?

**Comment by mrfixit2001** [comment]
I have had others report this as well, I believe it's a kernel issue. Will be investigating a fix.

**Comment by mrfixit2001** [comment]
This has been corrected in the new release!
