### ISSUE TITLE
WIFI SDIO trick or Patchset

### ISSUE THREAD

**Issue by NoDiskNoFun** [mrfixit2001/debian_builds#3]
First off: Thank you for your work!!!
I wanted to ask you how you get the SDIO WIFI module to work. I am running Arch Linux now and i tried to boot your kernel but it did not work (seems like some kind of firmware was not found, but i did a full copy of /lib/firmware). I also tried to enable all SDIO related options in kernel-config and built it against Mainline 4.19. Building did work but WIFI cannot be detected. I am asking you to either share your trick to get Linux to detect SDIO WIFI or alternatively, as open source programming generally would suggest, to share the complete patchset and/or config with the community.

**Comment by mrfixit2001** [comment]
I haven't published my kernel source itself yet. But I did write this patch for Batocera today which should outline the minimum requirements to get these features enabled. Hasn't been tested yet, as my kernel has an enormous amount of backports from mainline in it so I had to write this patch specifically for the "stock" rockchip kernel. Basically I'm saying I cannot guarantee how it will function without all the driver updates I've back-ported, but I think it's sufficient to enable everything.

https://github.com/batocera-linux/batocera.linux/pull/462/commits/9fe4442ffbb8a56850eedad8ceef1b147d0ef192
