### ISSUE TITLE
AMPAK AP6359SA support

### ISSUE THREAD

**Issue by gnthibault** [mrfixit2001/debian_builds#4]
Dear @mrfixit2001 
I was very happy to find your repo, thank you for the awesome work you are doing. I would like to setup AMPAK AP6359SA support for the BT/Wifi chip provided by pine64 on my distribution (ubuntu 18 from armbian), but unfortunately, I did not managed to find the package/source code for this chip.

How did you do to find it ?

Thank you very much for your help.

Regards

**Comment by mrfixit2001** [comment]
@gnthibault - thank you for reaching out!
The AP6359SA uses the Broadcom chipset BCM4359. The kernel drivers for this exist already within the Linux kernel, I just needed to patch them to find the correct firmware files, and the userspace then requires those firmware files in the correct location. I tried a number of sources for the firmware and the only ones that worked well were located at the following location:
https://github.com/kszaq/brcmfmac_sdio-firmware-aml/tree/master/firmware/brcm
Hope this helps!

**Comment by gnthibault** [comment]
Thank you very much, I must admit that I don't know much about firmware "loading". I'll see if I can learn how this work, otherwise, I will start by trying out your next release and see where things are located in the source. (I was more used to load modules at boot or after boot than kernel patching).

Again outstanding work thank you, I close the issue, as I saw that you are answering on pine64 discord.

**Comment by weskerfoot** [comment]
So does it work now or not? I'm trying to get this working right now and it's unclear as to whether the drivers are in the latest build or not.
