### ISSUE TITLE
Partition script doesn't work with eMMC

### ISSUE THREAD

**Issue by xperia64** [mrfixit2001/debian_builds#5]
My eMMC module shows three more block devices below the last partition in lsblk.
mmcblk1boot0, mmcblk1boot1, and mmcblk1rpmb. It thinks the last one is the home partition, which it isn't. This should probably be made more robust, but excluding these block devices would be enough.

**Comment by mrfixit2001** [comment]
Thanks for the detail! So I can be sure I understand your setup, are you booting from SD with an eMMC installed, booting from eMMC with an SD installed, or just booting from eMMC with no SD at all? I'd like to test with the same setup.

**Comment by xperia64** [comment]
Just eMMC, no SD.

**Comment by mrfixit2001** [comment]
Thanks. Which board? I will test as time permits.

**Comment by xperia64** [comment]
The RockPro64.

**Comment by mrfixit2001** [comment]
Thanks for reporting this. I unfortunately didn't have time to fix it in the latest release, but I have it fixed and will be sure it is included in the next one.
Replace line 22 in /usr/bin/partbootscript.sh with this:
     HOMEPART=$(lsblk --output NAME | grep ${HOMEPART}p | tail -1 | sed 's/.*-//')
The only change is the "p" at the end of homepart. 

Sorry for the issue! I'll leave this open for visibility for others until the next release.

**Comment by crushfx** [comment]
Thank you for the contribution! Unfortunately the pcie slot doesn't work on the rockpro64 board (kernel 4.4.171 from the rockpro64-debian-mrfixit.img image)

[    2.130570] of_get_named_gpiod_flags: parsed 'ep-gpios' property of node '/pcie@f8000000[0]' - status (0)
[    2.130732] rockchip-pcie f8000000.pcie: Looking up vpcie12v-supply from device tree
[    2.132423] rockchip-pcie f8000000.pcie: Looking up vpcie3v3-supply from device tree
[    2.132531] rockchip-pcie f8000000.pcie: Looking up vpcie1v8-supply from device tree
[    2.132657] rockchip-pcie f8000000.pcie: Looking up vpcie0v9-supply from device tree
[    2.132705] rockchip-pcie f8000000.pcie: missing optional "memory-region" property
[    2.132710] rockchip-pcie f8000000.pcie: missing optional "rockchip,dma_trx_enabled" property
[    2.132714] rockchip-pcie f8000000.pcie: missing optional "rockchip,deferred" property
[    2.132726] rockchip-pcie f8000000.pcie: enabled vpcie12v regulator
[    2.132730] rockchip-pcie f8000000.pcie: enabled vpcie3v3 regulator
[    2.132733] rockchip-pcie f8000000.pcie: enabled vpcie1v8 regulator
[    2.132737] rockchip-pcie f8000000.pcie: enabled vpcie0v9 regulator
[    2.132740] rockchip-pcie f8000000.pcie: calling really probe
[    2.132743] rockchip-pcie f8000000.pcie: PCIe asserting reset
[    2.132767] rockchip-pcie f8000000.pcie: advertising gen1 training
[    2.132793] rockchip-pcie f8000000.pcie: PCIe reset released
[    2.667479] rockchip-pcie f8000000.pcie: PCIe link training gen1 timed out.
[    2.667484] rockchip-pcie f8000000.pcie: init port failed
[    2.667502] rockchip-pcie f8000000.pcie: probe init failed
[    2.667529] rockchip-pcie f8000000.pcie: PCIe probe failed.
[    2.667805] rockchip-pcie: probe of f8000000.pcie failed with error -110
[    2.669021] dwmmc_rockchip fe310000.dwmmc: detected pcie initialized, continuing...

**Comment by mrfixit2001** [comment]
Closing - fix included in the last few releases
