### ISSUE TITLE
pcie nvme don't work

### ISSUE THREAD

**Issue by FrankM64** [mrfixit2001/debian_builds#6]
Hello Mr.Fixit,

wlan is working but no pcie nvme ssd on rockpro64.

[dmesg](https://pastebin.com/ZHdVW773) for you.

**Comment by mrfixit2001** [comment]
Update coming this week that should resolve :)

**Comment by mrfixit2001** [comment]
@bullet64 - Frank - thanks for reporting this! As you know, substantial progress has been made in the latest release in supporting PCIe + SDIO. We've spoken outside of GitHub regarding the fact that you are still experiencing some troubles. Interestingly, I have 3 other testers with NVMe who all have success in making the build work for their NVMe drives. When you can, please provide updated DMESG of your boot attempts for further analysis.

**Comment by FrankM64** [comment]
When someone has this problem, please remove pin 10 from your uart connection. Then the ROCKPro64 will boot fine with wifi & pcie nvme ssd.

Sorry @mrfixit2001 for these issue and thanks for your work!
