### ISSUE TITLE
raid support

### ISSUE THREAD

**Issue by franz82** [mrfixit2001/debian_builds#8]
Hi,
is there any plan to add raid support?
Seems missing:

```
# uname -a
Linux cnas 4.4.171 #1 SMP Fri Feb 22 15:44:29 EST 2019 aarch64 GNU/Linux
# modprobe raid1
modprobe: FATAL: Module raid1 not found in directory /lib/modules/4.4.171
```

Regards,
-f

**Comment by mrfixit2001** [comment]
Yes, I will include the raid drivers in the next release :) thanks!

**Comment by mrfixit2001** [comment]
I have added RAID drivers to the kernel in the latest release
