### ISSUE TITLE
pcie slot does not work (Intel i350-T4 network adapter)

### ISSUE THREAD

**Issue by crushfx** [mrfixit2001/debian_builds#9]
Thank you for the contribution! Unfortunately the pcie slot doesn't work on the rockpro64 board (kernel 4.4.171 from the rockpro64-debian-mrfixit.img image)

Here is what I get with an Intel i350-T4 network adapter:

[ 2.130570] of_get_named_gpiod_flags: parsed 'ep-gpios' property of node '/pcie@f8000000[0]' - status (0)
[ 2.130732] rockchip-pcie f8000000.pcie: Looking up vpcie12v-supply from device tree
[ 2.132423] rockchip-pcie f8000000.pcie: Looking up vpcie3v3-supply from device tree
[ 2.132531] rockchip-pcie f8000000.pcie: Looking up vpcie1v8-supply from device tree
[ 2.132657] rockchip-pcie f8000000.pcie: Looking up vpcie0v9-supply from device tree
[ 2.132705] rockchip-pcie f8000000.pcie: missing optional "memory-region" property
[ 2.132710] rockchip-pcie f8000000.pcie: missing optional "rockchip,dma_trx_enabled" property
[ 2.132714] rockchip-pcie f8000000.pcie: missing optional "rockchip,deferred" property
[ 2.132726] rockchip-pcie f8000000.pcie: enabled vpcie12v regulator
[ 2.132730] rockchip-pcie f8000000.pcie: enabled vpcie3v3 regulator
[ 2.132733] rockchip-pcie f8000000.pcie: enabled vpcie1v8 regulator
[ 2.132737] rockchip-pcie f8000000.pcie: enabled vpcie0v9 regulator
[ 2.132740] rockchip-pcie f8000000.pcie: calling really probe
[ 2.132743] rockchip-pcie f8000000.pcie: PCIe asserting reset
[ 2.132767] rockchip-pcie f8000000.pcie: advertising gen1 training
[ 2.132793] rockchip-pcie f8000000.pcie: PCIe reset released
[ 2.667479] rockchip-pcie f8000000.pcie: PCIe link training gen1 timed out.
[ 2.667484] rockchip-pcie f8000000.pcie: init port failed
[ 2.667502] rockchip-pcie f8000000.pcie: probe init failed
[ 2.667529] rockchip-pcie f8000000.pcie: PCIe probe failed.
[ 2.667805] rockchip-pcie: probe of f8000000.pcie failed with error -110
[ 2.669021] dwmmc_rockchip fe310000.dwmmc: detected pcie initialized, continuing...

**Comment by mrfixit2001** [comment]
Thanks for reaching out!
I expect this isn't an issue with the pcie driver, just that the drivers for your intel card are not currently included. I'll see about adding them in the next version, but in the meantime you should be able to download them and load the modules yourself.

**Comment by crushfx** [comment]
Doesn't the pcie device need to be visible on the pcie bus first before the card is picked up the the igb driver? I am actually having trouble building the out of tree igb driver for the i350 card so I'm attempting to rebuild the kernel with the driver module in it.

**Comment by mrfixit2001** [comment]
There have been a huge number of fixes and backports to PCIe since this issue was opened. Most cards are working now. It's been reported that there are still some drivers not included, as well as that some cards simply will not be identified by the kernel unless connected using a separate powered riser. I'm going to close this issue for now, but please re-test and provide full dmesg if it still fails. Thanks!
